### PR TITLE
Fix leftover quantum operations in classical functions during the gradient passes

### LINKED ISSUE #437: [BUG] Gradient compilation failing when classical processing used with wires within a for loop
The following example fails with v0.4.0-dev:

```python
dev = qml.device("lightning.qubit", wires=4)

@qjit
@qml.qnode(dev)
def f(x):
    def cnot_loop(j):
        qml.CNOT(wires=[j, jnp.mod((j + 1), 4)])

    for_loop(0, 4, 1)(cnot_loop)()

    return qml.expval(qml.PauliZ(0))
```
```pycon
>>> qjit(grad(f))(0.65)
RuntimeError: Compilation failed:
grad.f:6:3: error: 'func.func' op cloned during the gradient pass is not free of quantum ops:
```

However, it worked fine with `v0.3.2`:

```pycon
>>> qjit(grad(f))(0.65)
array(0.)
```

Due to this regression, there are various examples in the documentation/catalyst whitepaper that no longer work.

Note: there may be a more generic version of the MVP example above, but that was the most generic I could make it.

### PR DESCRIPTION
**Pull request by dime10**
Resolves an issue in the gradient dialect brought to light by #397. The error raised is as follows:
> error: 'func.func' op cloned during the gradient pass is not free of quantum ops

The error is thrown when when a quantum function is cloned but with all of its quantum operations removed, in order to retain only the classical code. This is done in several places in the gradient dialect.

In this case, certain input programs (see linked issue) would still cause the gradient pass to be unable to remove all quantum operations from a function. A snippet of the offending IR would look like:
```mlir
%i0 = tensor.extract %idx : tensor<i64>
%q = quantum.extract %r[%i0]
%i1 = tensor.extract %idx : tensor<i64>
%q = quantum.insert %r[%i1], %q
```
Even though the qubit extraction and insertion are performed at the same index, the SSA value used in both operations is not the same, and so the operations are not automatically folded way. This folding is usually relied upon to remove all quantum operations from a function.

Applying CSE before the gradient pass resolves the issue.

fixes #437

### CODE REVIEW

**Review by josh146 — APPROVED** [review]
That was quick 🚤 thanks @dime10!

**Comment by dime10** [comment]
@erick-xanadu I implemented the single register & qubit reset in between transform tapes (https://github.com/PennyLaneAI/catalyst/pull/439/commits/626df4d73457bdb611a5756589defae8979765b9), if you want to give it a look.

**Review by erick-xanadu — APPROVED** [review]
Very smart solution!
