### ISSUE TITLE
Graph decomposition under capture=True fails on resource reps with abstract wires (Wire[n])

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/catalyst#3163]
### Summary

Under `qml.qjit(capture=True)`, Catalyst's graph-decomposition path (`from_plxpr/decompose.py`) crashes whenever a decomposition rule declares its resources using an **abstract-wire** resource rep (i.e. an `Operator2` instantiated with `pennylane.typing.Wire[n]`, e.g. `qml.SemiAdder(Wire[n], Wire[n], Wire[m])`). This is common for `register_resources` rules that describe cost without concrete wires — e.g. the phase-gradient decompositions of `RZ`/`SelectPauliRot` in PennyLane.

### Minimal reproduction

```python
import pennylane as qml
from pennylane.decomposition import register_resources
from pennylane.typing import Wire

qml.decomposition.enable_graph()

def _res(**_):
    return {qml.SemiAdder(Wire[2], Wire[2], Wire[1]): 1}   # abstract-wire resource rep

@register_resources(_res)
def _rx_to_semiadder(phi, wires):
    qml.SemiAdder([1, 2], [3, 4], [5])

@qml.qjit(capture=True)
@qml.transforms.decompose(gate_set={"SemiAdder", "GlobalPhase"},
                          fixed_decomps={qml.RX: _rx_to_semiadder})
@qml.qnode(qml.device("null.qubit", wires=6))
def circuit():
    qml.RX(0.5, 0)
    return qml.expval(qml.Z(0))

qml.specs(circuit, level="all-mlir")()
```

```
AttributeError: 'AbstractWires' object has no attribute 'num_wires'
  at frontend/catalyst/from_plxpr/decompose.py, _resource_num_wires
```

### Environment

- catalyst `0.16.0-dev86` (also reproduces on `main`; the `.num_wires` access was introduced in #3075 and is still present)
- pennylane `0.46.0-dev88`
- jax `0.7.1`

**Comment by Qottmann** [comment]
https://github.com/PennyLaneAI/catalyst/pull/3168 should provide a fix

**Comment by Qottmann** [comment]
Didn't realize that qp.decompose was the old/unmaintained pathway, problem doesnt persist with new catalyst.passes.graph_decomposition
