### ISSUE TITLE
[BUG] Gradient compilation failing when classical processing used with wires within a for loop

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/catalyst#437]
The following example fails with v0.4.0-dev:

```python
dev = qml.device("lightning.qubit", wires=4)

@qjit
@qml.qnode(dev)
def f(x):
    def cnot_loop(j):
        qml.CNOT(wires=[j, jnp.mod((j + 1), 4)])

    for_loop(0, 4, 1)(cnot_loop)()

    return qml.expval(qml.PauliZ(0))
```
```pycon
>>> qjit(grad(f))(0.65)
RuntimeError: Compilation failed:
grad.f:6:3: error: 'func.func' op cloned during the gradient pass is not free of quantum ops:
```

However, it worked fine with `v0.3.2`:

```pycon
>>> qjit(grad(f))(0.65)
array(0.)
```

Due to this regression, there are various examples in the documentation/catalyst whitepaper that no longer work.

Note: there may be a more generic version of the MVP example above, but that was the most generic I could make it.
