### PR TITLE
Fix AttributeError for abstract-wire resource reps in capture decomposition

### LINKED ISSUE #3163: Graph decomposition under capture=True fails on resource reps with abstract wires (Wire[n])
### Summary

Under `qml.qjit(capture=True)`, Catalyst's graph-decomposition path (`from_plxpr/decompose.py`) crashes whenever a decomposition rule declares its resources using an **abstract-wire** resource rep (i.e. an `Operator2` instantiated with `pennylane.typing.Wire[n]`, e.g. `qml.SemiAdder(Wire[n], Wire[n], Wire[m])`). This is common for `register_resources` rules that describe cost without concrete wires — e.g. the phase-gradient decompositions of `RZ`/`SelectPauliRot` in PennyLane.

### Minimal reproduction

```python
import pennylane as qml
from pennylane.decomposition import register_resources
from pennylane.typing import Wire

qml.decomposition.enable_graph()

def _res(**_):
    return {qml.SemiAdder(Wire[2], Wire[2], Wire[1]): 1}   # abstract-wire resource rep

@register_resources(_res)
def _rx_to_semiadder(phi, wires):
    qml.SemiAdder([1, 2], [3, 4], [5])

@qml.qjit(capture=True)
@qml.transforms.decompose(gate_set={"SemiAdder", "GlobalPhase"},
                          fixed_decomps={qml.RX: _rx_to_semiadder})
@qml.qnode(qml.device("null.qubit", wires=6))
def circuit():
    qml.RX(0.5, 0)
    return qml.expval(qml.Z(0))

qml.specs(circuit, level="all-mlir")()
```

```
AttributeError: 'AbstractWires' object has no attribute 'num_wires'
  at frontend/catalyst/from_plxpr/decompose.py, _resource_num_wires
```

### Environment

- catalyst `0.16.0-dev86` (also reproduces on `main`; the `.num_wires` access was introduced in #3075 and is still present)
- pennylane `0.46.0-dev88`
- jax `0.7.1`

### PR DESCRIPTION
**Pull request by Qottmann**
## Summary

`AbstractWires` (`pennylane.typing.Wire[n]`) exposes `__len__` but not `.num_wires`, unlike the concrete `Wires` class. `from_plxpr/decompose.py` accessed `.num_wires` directly in two places, crashing whenever a decomposition rule's resource representation used abstract wires.

Fixes #3163.

## Changes

- `_resource_num_wires`: `op_rep.wires.num_wires` → `len(op_rep.wires)`
- `_create_decomposition_rule`: `wire_spec.num_wires` → `len(wire_spec)`

## Test plan

Note: the repro goes on to hit a separate, pre-existing MLIR segfault unrelated to abstract wires, tracked separately in #3167.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Review by dime10 — APPROVED** [review]
Thanks, looks good to me! Typically we always want a new test case that reproduces the error for any bugfix PRs :)

**Comment by Qottmann** [comment]
> Typically we always want a new test case that reproduces the error for any bugfix PRs :)

Good point! Added ✅ 

Thanks for the quick review! Who could I tag next?
